[tool.poetry]
name = "tomlkit"
version = "0.8.0"
description = "Style preserving TOML library"
authors = ["SÃ©bastien Eustace <sebastien@eustace.io>"]
license = "MIT"

readme = "README.md"

homepage = "https://github.com/sdispater/tomlkit"
repository = "https://github.com/sdispater/tomlkit"

include = [
  { path = "tomlkit/py.typed" },
  { path = "tests", format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
PyYAML = "^6.0"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
  | tests/toml-test
)/
'''

[tool.isort]
profile = "black"
force_single_line = true
atomic = true
lines_after_imports = 2
lines_between_types = 1

known_first_party = ["tomlkit"]
known_third_party = ["pytest"]

[build-system]
requires = ["poetry-core>=1.0.0a9"]
build-backend = "poetry.core.masonry.api"

[tool.pyprojectx]
poetry = "poetry==1.1.12"
black = "black==21.12b0"
isort = "isort==5.10.1"
flake8 = "flake8==4.0.1"
pre-commit = "pre-commit"
sphinx ="""\
sphinx==4.3.2
furo==2021.11.23"""

[tool.pyprojectx.aliases]
install = "poetry install"
outdated = "poetry show --outdated"
clean = """\
rm -r .venv
rm -r .pytest_cache
rm -r dist"""
clean-all = """\
pw@clean
rm -r .pyprojectx"""
format-code = "black tomlkit && pw@isort tomlkit"
test = "poetry run pytest tests/"
lint = "flake8 tomlkit"
check-black = "black tomlkit --check"
check = "pw@check-black && pw@lint && pw@test"
build = "pw@install && pw@check && pw@poetry build"
generate-docs = "@sphinx: sphinx-build docs build/docs"

[tool.pyprojectx.os.win.aliases]
clean = """\
rmdir /s/q .venv
rmdir /s/q .pytest_cache
rmdir /s/q dist"""
clean-all = """\
pw@clean
rmdir /s/q .pyprojectx"""
