[tool.poetry]
name = "tomlkit"
version = "0.4.3"
description = "Style preserving TOML library"
authors = ["SÃ©bastien Eustace <sebastien@eustace.io>"]
license = "MIT"

readme = "README.md"

homepage = "https://github.com/sdispater/tomlkit"
repository = "https://github.com/sdispater/tomlkit"

[tool.poetry.dependencies]
python = "~2.7 || ^3.4"

# enum34 is needed for Python 2.7
enum34 = { version = "^1.1", python = "~2.7" }

# The typing module is not in the stdlib in Python 2.7 and 3.4
typing = { version = "^3.6", python = "~2.7 || ~3.4" }

[tool.poetry.dev-dependencies]
pytest = "^3.6"
pytest-cov = "^2.5"
black = { version = "^18.6b4", python = "^3.6" }
pre-commit = "^1.10"
tox = "^3.1"


[tool.black]
line-length = 88
py36 = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
  | tests/toml-test
)/
'''
